services:
  videoflix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - ./backend:/usr/src/app
      - ./static_volume:/usr/src/app/staticfiles
    working_dir: /usr/src/app
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:latest"
    container_name: redis
    # volumes:
    #   - type: bind
    #     source: ./redis.conf
    #     target: /usr/local/etc/redis/redis.conf
    command: ["redis-server"]
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
