version: "3"

services:
  videoflix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - C:/00_DEV/videoflic_backend/backend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:latest"
    container_name: redis
    volumes:
      - C:/00_DEV/videoflic_backend/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
